const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
require('../velha-dados.js');const d=globalThis.OPC_VELHA_DATA,c=require('../velha-core.js');
const byName=name=>d.players.find(p=>p.name===name);
const has=(name,cat)=>byName(name).categories.includes(cat);
assert(d.players.length>=200);assert.equal(d.boards.length,1120);assert.equal(new Set(d.players.map(p=>p.id)).size,d.players.length);
for(const p of d.players){assert(p.name&&p.modes.length&&p.categories.length&&p.sources.length);assert(p.photo.author&&p.photo.licenseUrl&&p.photo.filePage);assert(fs.existsSync(path.join(__dirname,'..',p.photo.path)));}
assert(has('Romário','club:fluminense')&&has('Romário','club:flamengo'));assert(has('Ronaldinho','club:fluminense')&&has('Ronaldinho','club:flamengo'));assert(has('Gerson','club:fluminense')&&has('Gerson','club:flamengo'));
assert(has('Ronaldo','club:corinthians'));assert(has('Kaká','club:realmadrid'));assert(has('Marcelo','club:realmadrid'));assert(has('Vinícius Júnior','club:realmadrid'));
for(const name of ['Martin Ødegaard','Declan Rice','William Saliba','Nicolò Barella','Roberto Carlos','Romário'])assert(!has(name,'award:ballondor'),name+' não venceu a Bola de Ouro europeia');
for(const name of ['Cristiano Ronaldo','Kaká','Lionel Messi','Rivaldo','Ronaldinho','Ronaldo','Zidane'])assert(has(name,'award:ballondor'));
assert(!has('Achraf Hakimi','award:worldcup'));assert(!has('Neymar','award:copaamerica'));assert(!has('Ronaldo','award:champions'));assert(!has('Denzel Dumfries','club:realmadrid'));assert(!has('Felipe Melo','award:copaamerica'));
for(const name of ['Emiliano Martínez','Julián Álvarez','Nicolás Tagliafico','Lionel Messi','Romário','Ronaldo'])assert(has(name,'award:worldcup'));
for(const name of ['Yuri Alberto','Paulinho','Germán Cano','Fred','Gabriel Barbosa','Romário'])assert(has(name,'award:brtop'));
function assignment(sets){const order=sets.map((s,i)=>i).sort((a,b)=>sets[a].length-sets[b].length),used=new Set();const walk=k=>{if(k===9)return true;for(const p of sets[order[k]]){if(used.has(p.id))continue;used.add(p.id);if(walk(k+1))return true;used.delete(p.id);}return false;};return walk(0);}
for(const b of d.boards){assert.equal(new Set([...b.rows,...b.cols]).size,6);const sets=Array.from({length:9},(_,i)=>c.answers(d,b,i));assert.deepEqual(sets.map(s=>s.length),b.counts);assert(sets.every(s=>s.length>=(b.difficulty==='normal'?3:2)));if(b.difficulty==='hard')assert(sets.some(s=>s.length===2));assert(assignment(sets));const next=c.chooseBoard(d,b.mode,b.difficulty,b.id,()=>0);assert(next.rows.every((x,i)=>x!==b.rows[i])&&next.cols.every((x,i)=>x!==b.cols[i]));}
for(const mode of Object.keys(d.modes))for(const difficulty of ['normal','hard'])assert.equal(d.boards.filter(b=>b.mode===mode&&b.difficulty===difficulty).length,80);
for(const line of c.lines)for(const owner of [0,1]){const cells=Array(9).fill(null);line.forEach(i=>cells[i]={owner,playerId:String(i)});assert.deepEqual(c.winner(cells),{owner,line});}
const synthetic={players:Array.from({length:30},(_,i)=>({id:String(i),modes:['test'],categories:['r1','r2','r3','c1','c2','c3']})),boards:[{id:'a',mode:'test',difficulty:'normal',rows:['r1','r2','r3'],cols:['c1','c2','c3']},{id:'b',mode:'test',difficulty:'normal',rows:['r2','r3','r1'],cols:['c2','c3','c1']}]};
let s=c.start(synthetic,{mode:'test',difficulty:'normal',target:3,steal:true},()=>0);assert(!c.apply(synthetic,s,0,'0',1).ok);assert(!c.apply(synthetic,s,-1,'0').ok);assert(!c.apply(synthetic,s,0,'absent').ok);
s=c.apply(synthetic,s,0,'0').state;s=c.apply(synthetic,s,0,'1').state;assert.equal(s.cells[0].owner,1);assert.equal(s.steals[1],1);assert(!c.apply(synthetic,s,0,'0').ok,'Nome roubado continua consumido');
s=c.apply(synthetic,s,1,'2').state;s=c.apply(synthetic,s,1,'3').state;assert.equal(s.steals[1],2);s=c.apply(synthetic,s,2,'4').state;assert(!c.apply(synthetic,s,2,'5').ok,'Não existe terceiro roubo');
let no=c.start(synthetic,{mode:'test',difficulty:'normal',target:1,steal:false},()=>0);no=c.apply(synthetic,no,0,'0').state;assert(!c.apply(synthetic,no,0,'1').ok);
const wrong={...synthetic,players:[...synthetic.players,{id:'wrong',modes:['test'],categories:['r1']}]};let w=c.start(wrong,{mode:'test',difficulty:'normal',target:1,steal:false},()=>0);const r=c.apply(wrong,w,0,'wrong');assert(r.ok&&!r.correct);assert.equal(r.state.turn,1);assert(r.state.cells.every(x=>x===null));assert.equal(r.state.moves,1);
let series=c.start(synthetic,{mode:'test',difficulty:'normal',target:2,steal:false},()=>0);for(const [cell,id] of [[0,'0'],[3,'1'],[1,'2'],[4,'3'],[2,'4']])series=c.apply(synthetic,series,cell,id).state;assert.equal(series.result.winner,0);assert.deepEqual(series.score,[1,0]);assert(!series.matchEnded);const fresh=c.nextRound(synthetic,series,()=>0);assert.equal(fresh.turn,1);assert.equal(fresh.round,2);assert(fresh.used.length===0&&fresh.cells.every(x=>x===null));assert.notEqual(fresh.boardId,series.boardId);
let draw=c.start(synthetic,{mode:'test',difficulty:'normal',target:1,steal:false},()=>0);for(let i=0;i<40;i++)draw=c.pass(draw).state;assert(draw.roundEnded&&draw.result.winner===null);assert.deepEqual(draw.score,[0,0]);
let fixed=c.start(synthetic,{mode:'test',difficulty:'normal',format:'rounds',target:1,steal:false},()=>0);for(let i=0;i<40;i++)fixed=c.pass(fixed).state;assert(fixed.matchEnded&&fixed.matchWinner===null,'Última rodada empatada encerra série fixa');assert.throws(()=>c.nextRound(synthetic,fixed));
let trailing={...structuredClone(series),config:{...series.config,format:'rounds',target:2},round:2,score:[1,0],roundEnded:false,matchEnded:false,cells:Array(9).fill(null),used:[],moves:39};trailing=c.pass(trailing).state;assert(trailing.matchEnded&&trailing.matchWinner===0,'Placar acumulado decide mesmo quando última rodada empata');
let botState=c.start(synthetic,{mode:'test',difficulty:'normal',target:1,steal:false},()=>0);botState.cells[0]={owner:0,playerId:'0'};botState.cells[1]={owner:0,playerId:'1'};botState.used=['0','1'];assert.equal(c.bot(synthetic,botState,()=>0).cell,2,'Bot termina sua linha');botState.turn=1;assert.equal(c.bot(synthetic,botState,()=>0).cell,2,'Bot bloqueia vitória imediata');
for(let i=0;i<150;i++){const b=d.boards[i%d.boards.length];let game=c.start(d,{mode:b.mode,difficulty:b.difficulty,target:1,steal:i%2===0});for(let j=0;j<40&&!game.roundEnded;j++){const m=c.bot(d,game);const out=m?c.apply(d,game,m.cell,m.playerId):c.pass(game);assert(out.ok);if(m)assert(out.correct);game=out.state;}assert(game.roundEnded);assert.equal(new Set(game.used).size,game.used.length);}
console.log(`OK: ${d.players.length} jogadores, ${d.boards.length} grades; todas as interseções e nove respostas distintas; dados críticos, 8 linhas, roubo, bot, turnos, empate e série.`);
