import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createDraft,take,finish} from '../src/engine/draft';
import {attributes,type Position} from '../src/engine/types';
import {startCareer,simulate,transfer,replay,legacy,clubs} from '../src/engine/career';
function build(seed:string,pos:Position='ATA',speed:'fast'|'complete'='fast'){let d=createDraft({name:'Craque OPC',country:'Brasil',code:'br',position:pos,mode:'amador',speed,seed});for(const a of attributes)d=take(d,a);return finish(d,'2026-10-10T00:00:00.000Z');}
function full(seed:string,pos:Position='ATA',speed:'fast'|'complete'='fast'){let c=startCareer(build(seed,pos,speed));while(!c.retired){if(c.offers.length)c=transfer(c,c.seasons.length%2?c.offers[0]:'stay');c=simulate(c);}return c;}
test('carreira inteira reproduzida por seed e decisões, sem mutação',()=>{const c=full('REPLAY');assert.deepEqual(replay(c.build,c.decisions,c.seasons.length),c);assert.deepEqual(full('REPLAY'),c);const first=startCareer(build('PURE'));simulate(first);assert.equal(first.seasons.length,0);assert.throws(()=>transfer(first,'br1'));});
test('Fast e Completa produzem os mesmos resultados',()=>{const a=full('SAME','ATA','fast'),b=full('SAME','ATA','complete');assert.deepEqual(a.seasons,b.seasons);assert.deepEqual(a.decisions,b.decisions);assert.equal(a.retirement,b.retirement);});
test('500 carreiras: limites por posição, aposentadoria, finais e propostas',()=>{let finals=0,offers=0,gold=0;for(let i=0;i<500;i++){const c=full('COHORT-'+i,i%4===0?'GOL':i%4===1?'ZAG':i%4===2?'MAR':'ATA');assert.ok(c.retired);assert.equal(c.seasons[0].age,16);assert.equal(c.seasons.at(-1)!.age,c.retirement);assert.ok(c.retirement>=35&&c.retirement<=42);for(const s of c.seasons){assert.ok(s.games>=8&&s.games<=60);assert.ok(s.goals>=0&&s.goals<=55);assert.ok(s.assists>=0&&s.assists<=30);assert.ok(s.cleanSheets<=s.games);assert.ok(s.rating>=5&&s.rating<=9.5);assert.ok(s.leaguePlace>=1&&s.leaguePlace<=20);assert.ok(clubs.some(x=>x.id===s.clubId));if(c.build.config.position==='GOL')assert.equal(s.goals,0);for(const f of s.finals){finals++;assert.equal(f.events.filter(x=>x.side===0).length,f.score[0]);assert.equal(f.events.filter(x=>x.side===1).length,f.score[1]);assert.equal(f.won,f.penalties?f.penalties[0]>f.penalties[1]:f.score[0]>f.score[1]);assert.equal(s.trophies.includes(f.competition),f.won);}gold+=s.awards.filter(x=>x==='Bola de Ouro').length;}offers+=c.decisions.length;const l=legacy(c);assert.ok(l.level>=0&&l.level<=10);if(l.level>=6)assert.ok(l.gold>=2);if(l.level===10){assert.ok(l.gold>=7);assert.ok(l.world>=2);} }assert.ok(finals>0&&offers>0);assert.ok(gold<500);});
test('mercado bloqueia temporada até uma decisão válida',()=>{let c=startCareer(build('MARKET'));for(let i=0;i<25&&!c.offers.length&&!c.retired;i++)c=simulate(c);assert.ok(c.offers.length);assert.throws(()=>simulate(c));assert.throws(()=>transfer(c,'inexistente'));const next=transfer(c,'stay');assert.equal(next.clubId,c.clubId);assert.equal(next.offers.length,0);assert.ok(simulate(next).seasons.length>c.seasons.length);});
