import {test} from 'node:test';import assert from 'node:assert/strict';
import {athletes,athleteById,createDraft,take,finish,restore,overall,weights,VERSION} from '../src/engine/draft';
import {attributes,positions,type Config,type Stats} from '../src/engine/types';
const config:Config={name:'Craque OPC',country:'Brasil',code:'br',position:'ATA',mode:'pro',speed:'fast',seed:'OPC-TESTE'};
test('512 identidades reais distintas, fontes e notas válidas',()=>{assert.equal(athletes.length,512);assert.equal(new Set(athletes.map(p=>p.id)).size,512);assert.equal(new Set(athletes.map(p=>p.country)).size,49);for(const p of athletes){assert(/^Q\d+$/.test(p.id));assert(p.name.trim()&&/^https:\/\//.test(p.source));assert(positions.includes(p.position));assert(p.era<=2020);for(const k of attributes)assert(Number.isInteger(p.stats[k])&&p.stats[k]>=1&&p.stats[k]<=((k==='skills'||k==='weakFoot')?5:99));assert.equal(p.overall,overall(p.stats,p.position));}for(const name of ['Pelé','Neymar','Ronaldo','Ronaldinho','Romário'])assert(athletes.some(p=>p.name===name));});
test('oito giros únicos e reproduzíveis em 1000 seeds e ambos os modos',()=>{for(let i=0;i<1000;i++)for(const mode of ['amador','pro'] as const){const c={...config,mode,seed:'SEED-'+i};const d=createDraft(c);assert.equal(d.deck.length,8);assert.equal(new Set(d.deck).size,8);assert.deepEqual(d,createDraft(c));assert.deepEqual(d.deck,createDraft({...c,speed:'complete'}).deck);if(mode==='amador')assert(d.deck.filter(id=>athleteById.get(id)!.overall>=90).length>=2);}});
test('cada escolha é permanente, motor puro e oitavo giro encerra',()=>{let d=createDraft(config);for(const key of attributes){const before=structuredClone(d);const next=take(d,key);assert.deepEqual(d,before);assert.equal(next.picks.at(-1)!.value,athleteById.get(d.deck[d.picks.length])!.stats[key]);assert.throws(()=>take(next,key));d=next;}assert.throws(()=>take(d,'pace'));const build=finish(d,'2026-10-10T00:00:00Z');assert.equal(build.picks.length,8);assert.deepEqual(build,finish(d,'2026-10-10T00:00:00Z'));assert.equal(Object.keys(build.stats).length,8);});
test('seed e decisões reproduzem a ficha, posição muda a avaliação',()=>{let a=createDraft(config),b=createDraft(config);for(const k of attributes){a=take(a,k);b=take(b,k);}assert.equal(finish(a,'x').id,finish(b,'x').id);const defensive:Stats={pace:70,shooting:20,passing:80,dribbling:35,defending:98,physical:90,skills:1,weakFoot:3};assert(overall(defensive,'GOL')>overall(defensive,'ATA')+25);for(const p of positions)assert(Math.abs(weights[p].reduce((a,b)=>a+b,0)-1)<.00001);});
test('retomada revalida seed, escolhas e valores; corrupção é recusada',()=>{let d=createDraft(config);d=take(d,'dribbling');d=take(d,'physical');assert.deepEqual(restore(JSON.parse(JSON.stringify(d))),d);assert.equal(restore({...d,version:'outro'}),null);assert.equal(restore({...d,deck:[...d.deck].reverse()}),null);assert.equal(restore({...d,picks:d.picks.map((p,i)=>i===0?{...p,value:99}:p)}),null);assert.equal(restore(null),null);assert.equal(restore({}),null);assert.throws(()=>finish(d,'x'));assert.throws(()=>createDraft({...config,seed:''}));assert.equal(d.version,VERSION);});
