import type {Build} from './types';
import {random,shuffled} from './random';
export const ENGINE='opc-career-2';
export interface Club {id:string;name:string;country:string;continent:string;league:string;strength:number}
const groups:[string,string,string,string,string[],number[]][]=[
 ['br','Brasil','SA','Brasileirão',['Santos','Flamengo','Palmeiras','Corinthians','São Paulo','Fluminense','Botafogo','Grêmio','Cruzeiro','Vasco','Bahia','Fortaleza'],[71,85,85,77,79,78,80,76,74,70,73,72]],
 ['en','Inglaterra','EU','Premier League',['Manchester City','Liverpool','Arsenal','Chelsea','Manchester United','Tottenham','Brighton'],[91,90,88,86,82,81,75]],
 ['es','Espanha','EU','LaLiga',['Real Madrid','Barcelona','Atlético de Madrid','Sevilla','Villarreal','Real Sociedad'],[94,91,86,76,80,78]],
 ['it','Itália','EU','Serie A',['Inter','Milan','Juventus','Napoli','Roma','Atalanta'],[89,85,86,86,80,84]],
 ['de','Alemanha','EU','Bundesliga',['Bayern','Borussia Dortmund','Bayer Leverkusen','RB Leipzig','Frankfurt'],[92,85,87,82,79]],
 ['fr','França','EU','Ligue 1',['PSG','Marseille','Monaco','Lyon','Lille'],[91,81,80,77,79]],
 ['ar','Argentina','SA','Liga Argentina',['River Plate','Boca Juniors','Racing'],[80,78,75]],
 ['us','Estados Unidos','NA','MLS',['Inter Miami','LA Galaxy','Los Angeles FC'],[73,69,73]],
 ['mx','México','NA','Liga MX',['América','Monterrey','Tigres'],[77,76,75]],
 ['sa','Arábia Saudita','AS','Liga Saudita',['Al-Hilal','Al-Nassr','Al-Ittihad'],[80,78,77]],
 ['jp','Japão','AS','J1 League',['Vissel Kobe','Urawa Reds'],[70,69]]];
export const clubs:Club[]=groups.flatMap(([prefix,country,continent,league,names,strengths])=>names.map((name,i)=>({id:prefix+i,name,country,continent,league,strength:strengths[i]})));
export const clubById=(id:string)=>clubs.find(c=>c.id===id)!;
export interface FinalEvent {minute:number;side:0|1;author:string}
export interface Final {competition:string;opponent:string;events:FinalEvent[];score:[number,number];penalties?:[number,number];won:boolean}
export interface Award {name:string;candidates:string[];winner:string;won:boolean}
export interface SeasonResult {year:number;age:number;clubId:string;overall:number;games:number;goals:number;assists:number;cleanSheets:number;rating:number;leaguePlace:number;trophies:string[];awards:string[];finals:Final[];ceremonies:Award[]}
export interface CareerState {version:string;build:Build;origin:string;clubId:string;retirement:number;seasons:SeasonResult[];offers:string[];decisions:string[];lastTransfer:number;retired:boolean}
const identity=(b:Build)=>JSON.stringify([b.config.seed,b.config.mode,b.config.position,b.picks]);
const cap=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
export function startCareer(build:Build):CareerState {const rng=random(ENGINE+'|'+identity(build)+'|start'),pool=clubs.filter(c=>c.continent===(build.config.code==='br'||['ar','uy','co','cl','ec','pe','py'].includes(build.config.code)?'SA':'EU')&&c.strength<81),origin=pool[Math.floor(rng()*pool.length)].id;return {version:ENGINE,build,origin,clubId:origin,retirement:35+Math.floor(rng()*6)+(build.config.position==='GOL'?2:0),seasons:[],offers:[],decisions:[],lastTransfer:-3,retired:false};}
export function transfer(c:CareerState,id:string):CareerState {if(c.retired||!c.offers.length||!(id==='stay'||c.offers.includes(id)))throw Error('Proposta inválida');return {...c,clubId:id==='stay'?c.clubId:id,offers:[],lastTransfer:id==='stay'?c.lastTransfer:c.seasons.length,decisions:[...c.decisions,id]};}
export function simulate(c:CareerState):CareerState {if(c.retired||c.offers.length)throw Error('Resolva a proposta antes de avançar');const index=c.seasons.length,age=16+index,year=2026+index,club=clubById(c.clubId),cfg=c.build.config,rng=random(ENGINE+'|'+identity(c.build)+'|'+index+'|'+c.decisions.join(',')+'|'+c.clubId),roll=()=>rng(),base=c.build.overall,development=age<25?-(25-age)*1.4:age>30?-(age-30)*(cfg.position==='GOL'?1.15:1.7):0,ovr=Math.round(cap(base+development+(cfg.mode==='amador'?3:0)+(roll()-.5)*3,25,99)),quality=ovr/100,league=club.continent==='EU'?1.08:club.continent==='SA'?1:.9,role=cap((ovr-club.strength+25)/35,.18,1),games=Math.round(cap(18+role*30+roll()*10-(roll()<.08?12:0),8,60)),attacking=['ATA','SA','PON'].includes(cfg.position),mid=['MAR','MEI'].includes(cfg.position),goalRate=cfg.position==='GOL'?0:attacking?.12+(c.build.stats.shooting/100)*.52:mid?.07+quality*.16:.015+quality*.055,goals=cfg.position==='GOL'?0:Math.round(cap(games*goalRate*quality/league*(.65+roll()*.7),0,55)),assists=cfg.position==='GOL'?Math.floor(roll()*3):Math.round(cap(games*(mid||cfg.position==='PON'?.3:.14)*(c.build.stats.passing/100)*(.7+roll()*.8),0,30)),cleanSheets=cfg.position==='GOL'?Math.round(games*cap(.12+quality*.27+(club.strength-75)/160,.08,.65)*(.8+roll()*.4)):0,rating=Math.round(cap(5.5+quality*1.7+(goals+assists+cleanSheets*.8)/games*.8+(roll()-.5)*.6,5,9.5)*10)/10,team=club.strength+(ovr-club.strength)*role*.16,leaguePlace=Math.round(cap(1+(100-team)/3+(roll()-.5)*9,1,20)),trophies:string[]=[],finals:Final[]=[],awards:string[]=[],ceremonies:Award[]=[];
if(leaguePlace===1)trophies.push(club.league);
function final(competition:string,international=false){const opponents=clubs.filter(x=>x.id!==club.id&&(international?x.continent===club.continent:x.league===club.league)),opponent=opponents[Math.floor(roll()*opponents.length)]||clubs[0],chance=cap(.5+(team-opponent.strength)/100,.18,.82),events:FinalEvent[]=[];let score:[number,number]=[0,0];for(let t=10;t<=90;t+=10){if(roll()<.23){const side:0|1=roll()<chance?0:1;score[side]++;events.push({minute:t-Math.floor(roll()*6),side,author:side===0&&roll()<quality*.55&&cfg.position!=='GOL'?cfg.name:side===0?'Companheiro de equipe':'Atacante adversário'});}}let penalties:[number,number]|undefined;if(score[0]===score[1]){const won=roll()<chance;penalties=won?[5,4]:[4,5];}const won=penalties?penalties[0]>penalties[1]:score[0]>score[1];const national=['Brasil','Argentina','França','Alemanha','Espanha','Portugal','Inglaterra','Itália'].filter(n=>n!==cfg.country);finals.push({competition,opponent:competition==='Copa do Mundo'?national[Math.floor(roll()*national.length)]:opponent.name,events,score,penalties,won});if(won)trophies.push(competition);}
if(roll()<cap((team-55)/160,.05,.28))final(club.country==='Brasil'?'Copa do Brasil':'Copa nacional');
const continental=club.continent==='EU'?(leaguePlace<=4?'Champions League':'Europa League'):club.continent==='SA'?(leaguePlace<=6?'Libertadores':'Sul-Americana'):club.continent==='NA'?'Concachampions':'Liga dos Campeões da Ásia';
if(leaguePlace<=8&&roll()<cap((team-60)/200,.03,continental==='Champions League'?.16:.24))final(continental,true);
if(year%4===2&&age>=20&&ovr>=83&&roll()<.055+(ovr-83)*.004)final('Copa do Mundo',true);
const exceptional=ovr>=88&&rating>=7.6&&(goals>=24||assists>=17||cleanSheets>=22)&&(trophies.some(t=>['Champions League','Copa do Mundo','Libertadores'].includes(t))||goals>=35||rating>=8.1);
const rivals=Array.from({length:2},(_,i)=>''+['Mateo','Luca','Gabriel','Adam','Youssef','Enzo'][Math.floor(roll()*6)]+' '+['Silva','Moreau','Costa','Rossi','Benali','Walker'][(year+i)%6]);
function award(name:string,chance:number){const won=roll()<chance,candidates=shuffled([cfg.name,...rivals],roll),winner=won?cfg.name:rivals[Math.floor(roll()*rivals.length)];ceremonies.push({name,candidates,winner,won});if(won)awards.push(name);}
if(exceptional)award('Bola de Ouro',cap((ovr-84)/85+(cfg.mode==='amador'?.025:0),.01,.22));
if(goals>=23)award('Chuteira de Ouro',cap((goals-18)/70,.03,.35));
if(cfg.position==='GOL'&&cleanSheets>=18)award('Luva de Ouro',cap((cleanSheets-14)/60,.03,.35));
const season:SeasonResult={year,age,clubId:club.id,overall:ovr,games,goals,assists,cleanSheets,rating,leaguePlace,trophies,awards,finals,ceremonies},retired=age>=c.retirement,next={...c,seasons:[...c.seasons,season],retired,offers:[] as string[]};
if(!retired&&index>=3&&index-c.lastTransfer>=3&&roll()<.34){let pool=clubs.filter(x=>x.id!==club.id&&Math.abs(x.strength-(ovr+Math.max(0,rating-7)*4+Math.min(6,c.seasons.flatMap(s=>s.trophies).length)))<15);if(age>=33)pool=[...pool.filter(x=>x.continent!=='EU'),clubById(c.origin)];next.offers=shuffled([...new Map(pool.map(x=>[x.id,x])).values()],roll).slice(0,2).map(x=>x.id);}
return next;}
export const levels=['Jogador comum','Sensação de uma temporada','Estrela','Jogador histórico','Top 50 de todos os tempos','Um dos melhores da sua posição','Top 10 de todos os tempos','O melhor da sua posição na história','Top 5 de todos os tempos','Sempre citado no debate GOAT','O FENÔMENO'];
export function legacy(c:CareerState){const s=c.seasons,games=s.reduce((a,x)=>a+x.games,0),goals=s.reduce((a,x)=>a+x.goals,0),assists=s.reduce((a,x)=>a+x.assists,0),cleanSheets=s.reduce((a,x)=>a+x.cleanSheets,0),trophies=s.flatMap(x=>x.trophies),awards=s.flatMap(x=>x.awards),gold=awards.filter(x=>x==='Bola de Ouro').length,world=trophies.filter(x=>x==='Copa do Mundo').length,peak=Math.max(c.build.overall,...s.map(x=>x.overall)),regularity=s.filter(x=>x.rating>=7.5).length,score=Math.round(games*.3+goals*1.5+assists*1.2+cleanSheets*1.8+trophies.reduce((a,t)=>a+(t==='Copa do Mundo'?450:t==='Champions League'||t==='Libertadores'?180:60),0)+gold*500+awards.length*45+regularity*25+Math.max(0,peak-75)*20),thresholds=[0,500,1000,1700,2600,3400,4400,5200,6200,7400,9000],gates=[0,0,0,0,0,1,2,3,4,5,7];let level=0;for(let i=1;i<11;i++)if(score>=thresholds[i]&&gold>=gates[i]&&(i<10||(world>=2&&peak>=96)))level=i;return {games,goals,assists,cleanSheets,trophies,awards,gold,world,peak,score,level,title:levels[level]};}
export function replay(build:Build,decisions:string[],seasons:number):CareerState {let c=startCareer(build),cursor=0;for(let i=0;i<seasons;i++){if(c.offers.length){if(!decisions[cursor])throw Error('Decisão ausente');c=transfer(c,decisions[cursor++]);}c=simulate(c);}if(c.offers.length&&decisions[cursor])c=transfer(c,decisions[cursor++]);if(cursor!==decisions.length)throw Error('Decisões excedentes');return c;}
