import data from '../data/athletes.json';
import {attributes,positions,type Athlete,type Attribute,type Build,type Config,type Draft,type Stats,type Position} from './types';
import {hash,random,shuffled} from './random';
export const VERSION='opc-forja-1.0';
export const athletes=data as Athlete[];
export const athleteById=new Map(athletes.map(p=>[p.id,p]));
export const labels:Record<Attribute,string>={pace:'Velocidade',shooting:'Finalização',passing:'Passe',dribbling:'Drible',defending:'Defesa',physical:'Físico',skills:'Dribles ★',weakFoot:'Perna ruim ★'};
export const positionNames:Record<Position,string>={GOL:'Goleiro',ZAG:'Zagueiro',ALA:'Ala / lateral',VOL:'Volante',MEI:'Meio-campista',MAR:'Meia armador',PON:'Ponta',SA:'Segundo atacante',ATA:'Atacante'};
export const weights:Record<Position,number[]>={GOL:[.08,0,.15,.01,.5,.18,0,.08],ZAG:[.12,.02,.09,.03,.45,.23,.01,.05],ALA:[.25,.04,.18,.12,.24,.1,.02,.05],VOL:[.1,.05,.22,.1,.29,.17,.02,.05],MEI:[.12,.09,.29,.19,.12,.1,.03,.06],MAR:[.13,.13,.32,.23,.03,.05,.05,.06],PON:[.29,.19,.14,.24,.02,.04,.05,.03],SA:[.19,.3,.15,.23,.01,.05,.03,.04],ATA:[.19,.39,.07,.13,.01,.13,.03,.05]};
export function overall(stats:Stats,position:Position):number {return Math.max(1,Math.min(99,Math.round(attributes.reduce((sum,key,i)=>sum+stats[key]*(key==='skills'||key==='weakFoot'?20:1)*weights[position][i],0))));}
export function validateConfig(c:Config):void {if(!positions.includes(c.position)||!['amador','pro'].includes(c.mode)||!['fast','complete'].includes(c.speed)||!c.seed.trim()||c.seed.length>48||!c.name.trim()||c.name.length>28||!c.country||!c.code)throw Error('Configuração inválida. Confira nome, posição e seed.');}
export function createDraft(c:Config):Draft {validateConfig(c);const config={...c,name:c.name.trim(),seed:c.seed.trim()};const rng=random(VERSION+'|'+config.seed+'|'+config.mode);let pool=shuffled(athletes,rng);if(config.mode==='amador'){const elite=pool.filter(p=>p.overall>=90).slice(0,2),high=pool.filter(p=>p.overall>=82&&p.overall<90).slice(0,3),rest=pool.filter(p=>p.overall>=74&&!elite.includes(p)&&!high.includes(p)).slice(0,3);pool=shuffled([...elite,...high,...rest],rng);}return {version:VERSION,config,deck:pool.slice(0,8).map(p=>p.id),picks:[]};}
export function take(d:Draft,key:Attribute):Draft {if(d.version!==VERSION||!attributes.includes(key)||d.picks.length>=8||d.picks.some(p=>p.attribute===key))throw Error('Atributo já preenchido ou giro encerrado.');const player=athleteById.get(d.deck[d.picks.length]);if(!player)throw Error('Atleta indisponível.');return {...d,picks:[...d.picks,{athleteId:player.id,attribute:key,value:player.stats[key]}]};}
export function partial(d:Draft):Partial<Stats> {return Object.fromEntries(d.picks.map(p=>[p.attribute,p.value]));}
export function finish(d:Draft,createdAt:string):Build {if(d.picks.length!==8)throw Error('Complete os oito giros.');const stats=partial(d) as Stats;return {id:hash(JSON.stringify([VERSION,d.config,d.picks])).toString(16),createdAt,config:d.config,picks:d.picks,stats,overall:overall(stats,d.config.position)};}
export function restore(raw:unknown):Draft|null {try{const candidate=raw as Draft;if(candidate.version!==VERSION||!Array.isArray(candidate.picks)||candidate.picks.length>8)return null;let replay=createDraft(candidate.config);for(const p of candidate.picks){if(p.athleteId!==replay.deck[replay.picks.length])return null;replay=take(replay,p.attribute);if(replay.picks.at(-1)?.value!==p.value)return null;}if(JSON.stringify(replay.deck)!==JSON.stringify(candidate.deck))return null;return replay;}catch{return null;}}
