const fs=require('node:fs'),path=require('node:path');
require('../../repo/velha-dados.js');const source=global.OPC_VELHA_DATA;
const known=JSON.parse(fs.readFileSync('../data/velha/reviewed-identities.json','utf8'));
const hash=s=>[...s].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261);
const countries={Brazil:['Brasil','br'],Argentina:['Argentina','ar'],Uruguay:['Uruguai','uy'],France:['França','fr'],Germany:['Alemanha','de'],Italy:['Itália','it'],Spain:['Espanha','es'],England:['Inglaterra','gb-eng'],Portugal:['Portugal','pt'],Netherlands:['Países Baixos','nl'],Belgium:['Bélgica','be'],Sweden:['Suécia','se'],Croatia:['Croácia','hr'],Poland:['Polônia','pl'],Denmark:['Dinamarca','dk'],Norway:['Noruega','no'],Scotland:['Escócia','gb-sct'],Wales:['País de Gales','gb-wls'],Ireland:['Irlanda','ie'],Russia:['Rússia','ru'],Ukraine:['Ucrânia','ua'],Czechia:['Tchéquia','cz'],Serbia:['Sérvia','rs'],Hungary:['Hungria','hu'],Romania:['Romênia','ro'],Turkey:['Turquia','tr'],Japan:['Japão','jp'],'South Korea':['Coreia do Sul','kr'],Mexico:['México','mx'],Colombia:['Colômbia','co'],Chile:['Chile','cl'],Paraguay:['Paraguai','py'],Peru:['Peru','pe'],Ecuador:['Equador','ec'],Morocco:['Marrocos','ma'],Algeria:['Argélia','dz'],Nigeria:['Nigéria','ng'],Ghana:['Gana','gh'],Senegal:['Senegal','sn'],Cameroon:['Camarões','cm'],'Ivory Coast':['Costa do Marfim','ci'],Egypt:['Egito','eg'],Australia:['Austrália','au'],'United States':['Estados Unidos','us'],Canada:['Canadá','ca'],Switzerland:['Suíça','ch'],Austria:['Áustria','at'],Greece:['Grécia','gr'],Finland:['Finlândia','fi'],'Bosnia and Herzegovina':['Bósnia e Herzegovina','ba']};
const elite={'Pelé':97,'Neymar':92,'Ronaldo':96,'Ronaldinho':94,'Romário':94,'Lionel Messi':97,'Cristiano Ronaldo':96,'Zidane':94,'Kaká':92,'Rivaldo':93,'Roberto Carlos':92,'Cafu':92,'Garrincha':95,'Sócrates':91,'Zico':94,'Thierry Henry':93,'Zlatan Ibrahimović':90,'Andrés Iniesta':93,'Xavi':92,'Paolo Maldini':95,'Franco Baresi':94,'Gianluigi Buffon':96,'Manuel Neuer':94,'Iker Casillas':93,'Diego Maradona':97,'Johan Cruyff':96,'Franz Beckenbauer':95,'Lothar Matthäus':94,'Marco van Basten':94,'Gerd Müller':94,'Lev Yashin':96,'Bobby Charlton':94,'Eusébio':94,'Bobby Moore':93,'Dennis Bergkamp':91};
const profile={GOL:[61,13,67,30,92,82,1,3],ZAG:[66,35,61,47,85,84,2,3],ALA:[82,51,73,73,72,71,3,3],VOL:[66,55,78,67,77,79,2,3],MEI:[69,62,81,77,64,68,3,3],MAR:[74,70,85,84,36,61,4,4],PON:[88,72,71,85,27,59,4,3],SA:[78,84,72,82,25,70,4,4],ATA:[77,87,56,70,22,81,3,3]};
function role(s){if(s.includes('GOL'))return 'GOL';if(s.includes('ZAG')||s==='Defensor')return 'ZAG';if(/LE|LD|Lateral/.test(s))return 'ALA';if(s.includes('VOL'))return 'VOL';if(s.includes('MEI'))return 'MAR';if(s.includes('MC')||s==='Meio-campista')return 'MEI';if(/PD|PE|Ponta/.test(s))return 'PON';if(/ATA|Atacante/.test(s))return 'ATA';return null;}
const keys=['pace','shooting','passing','dribbling','defending','physical','skills','weakFoot'];
const weights={GOL:[.08,0,.15,.01,.5,.18,0,.08],ZAG:[.12,.02,.09,.03,.45,.23,.01,.05],ALA:[.25,.04,.18,.12,.24,.1,.02,.05],VOL:[.1,.05,.22,.1,.29,.17,.02,.05],MEI:[.12,.09,.29,.19,.12,.1,.03,.06],MAR:[.13,.13,.32,.23,.03,.05,.05,.06],PON:[.29,.19,.14,.24,.02,.04,.05,.03],SA:[.19,.3,.15,.23,.01,.05,.03,.04],ATA:[.19,.39,.07,.13,.01,.13,.03,.05]};
const pool=source.players.filter(p=>role(p.position||'')&&p.birth&&countries[p.nationality]&&+p.birth.slice(0,4)<=2008);
const eliteIdentity=Object.fromEntries(Object.keys(elite).map(name=>[name,known[name]||pool.filter(p=>p.name===name).sort((a,b)=>b.categories.filter(c=>c.startsWith('award:')).length-a.categories.filter(c=>c.startsWith('award:')).length)[0]?.identity]));
eliteIdentity['Pelé']='Q12897';eliteIdentity['Diego Maradona']='Q1751';eliteIdentity['Johan Cruyff']='Q13464';
const curated=pool.filter(p=>known[p.name]===p.identity||eliteIdentity[p.name]===p.identity);
// Stratified round-robin includes different eras and countries, rather than a fame-only list.
const buckets=new Map();for(const p of pool){const key=p.nationality+'-'+Math.floor((+p.birth.slice(0,4)+25)/20);const a=buckets.get(key)||[];a.push(p);buckets.set(key,a);}for(const a of buckets.values())a.sort((a,b)=>hash(a.identity)-hash(b.identity));
const selected=new Map(curated.map(p=>[p.identity,p]));const groups=[...buckets.values()].sort((a,b)=>a[0].nationality.localeCompare(b[0].nationality));for(let i=0;selected.size<512&&i<100;i++)for(const g of groups){if(selected.size>=512)break;if(g[i])selected.set(g[i].identity,g[i]);}
const usedNames=new Map();for(const p of selected.values())usedNames.set(p.name,(usedNames.get(p.name)||0)+1);
const result=[...selected.values()].slice(0,512).map(p=>{let position=role(p.position);const iconic=eliteIdentity[p.name]===p.identity;if(iconic&&['Ronaldo','Romário','Pelé','Cristiano Ronaldo'].includes(p.name))position='ATA';if(iconic&&['Zidane','Ronaldinho','Kaká','Zico','Diego Maradona'].includes(p.name))position='MAR';if(iconic&&['Lionel Messi','Dennis Bergkamp','Johan Cruyff'].includes(p.name))position='SA';const seed=hash(p.identity);const prestige=iconic?elite[p.name]:(63+seed%19+Math.min(5,p.categories.filter(c=>c.startsWith('award:')).length));const stats=Object.fromEntries(keys.map((k,i)=>{const variance=((seed>>>(i*3%24))%9)-4;let value=profile[position][i];if(i<6)value+=Math.round((prestige-78)*.85)+variance;else value+=prestige>=92?1:prestige<69?-1:0;return [k,Math.max(i<6?12:1,Math.min(i<6?99:5,value))];}));if(iconic)for(let i=0;i<6;i++)if(weights[position][i]>.13)stats[keys[i]]=Math.min(99,elite[p.name]+((seed>>i)%5)-2);const overall=Math.round(keys.reduce((sum,k,i)=>sum+stats[k]*(i>=6?20:1)*weights[position][i],0));const [country,code]=countries[p.nationality];return {id:p.identity,name:p.name,country,code,position,era:Math.min(2020,Math.round((+p.birth.slice(0,4)+26)/10)*10),overall,stats,tier:iconic?'icon':overall>=79?'gold':'silver',source:p.sources[0]};});
fs.mkdirSync('src/data',{recursive:true});fs.mkdirSync('public',{recursive:true});fs.writeFileSync('src/data/athletes.json',JSON.stringify(result,null,2));fs.writeFileSync('src/data/countries.json',JSON.stringify(Object.values(countries).map(([name,code])=>({name,code})).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')),null,2));fs.writeFileSync('public/athletes-sources.json',JSON.stringify({updated:'2026-10-10',method:'Identidades, nomes, nacionalidades e posição profissional reaproveitados da base OPC com fonte individual. Atributos são estimativas próprias de entretenimento, geradas por perfis de posição e ajustes editoriais; não são estatísticas oficiais ou dados de videogames comerciais. Década é uma referência aproximada baseada na data de nascimento mais 26 anos, limitada a 2020; não define um auge comprovado. Defesa em GOL representa a capacidade de impedir gols. Bandeiras são servidas pelo FlagCDN com fallback textual.',athletes:result.map(({id,name,country,position,era,source})=>({id,name,country,position,era,source}))},null,2));console.log({players:result.length,countries:new Set(result.map(p=>p.country)).size,eras:[...new Set(result.map(p=>p.era))].sort(),tiers:result.reduce((a,p)=>(a[p.tier]=(a[p.tier]||0)+1,a),{})});
